default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: happy123
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: Food_development
  username: postgres
  password: happy123
  pool: 5
  timeout: 5000


production:
  <<: *default
  database: Food_production
  username: Food
  password: <%= ENV['FOOD_DATABASE_PASSWORD'] %>
  username: postgres
  password: happy123
  pool: 5
  timeout: 5000
